package uz.momoit.lms_canvas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AttendanceDetailAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttendanceDetailAllPropertiesEquals(AttendanceDetail expected, AttendanceDetail actual) {
        assertAttendanceDetailAutoGeneratedPropertiesEquals(expected, actual);
        assertAttendanceDetailAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttendanceDetailAllUpdatablePropertiesEquals(AttendanceDetail expected, AttendanceDetail actual) {
        assertAttendanceDetailUpdatableFieldsEquals(expected, actual);
        assertAttendanceDetailUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttendanceDetailAutoGeneratedPropertiesEquals(AttendanceDetail expected, AttendanceDetail actual) {
        assertThat(expected)
            .as("Verify AttendanceDetail auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttendanceDetailUpdatableFieldsEquals(AttendanceDetail expected, AttendanceDetail actual) {
        assertThat(expected)
            .as("Verify AttendanceDetail relevant properties")
            .satisfies(e -> assertThat(e.getAttendanceEnum()).as("check attendanceEnum").isEqualTo(actual.getAttendanceEnum()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttendanceDetailUpdatableRelationshipsEquals(AttendanceDetail expected, AttendanceDetail actual) {
        assertThat(expected)
            .as("Verify AttendanceDetail relationships")
            .satisfies(e -> assertThat(e.getAttendance()).as("check attendance").isEqualTo(actual.getAttendance()));
    }
}
