package uz.momoit.lms_canvas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CalendarTodoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarTodoAllPropertiesEquals(CalendarTodo expected, CalendarTodo actual) {
        assertCalendarTodoAutoGeneratedPropertiesEquals(expected, actual);
        assertCalendarTodoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarTodoAllUpdatablePropertiesEquals(CalendarTodo expected, CalendarTodo actual) {
        assertCalendarTodoUpdatableFieldsEquals(expected, actual);
        assertCalendarTodoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarTodoAutoGeneratedPropertiesEquals(CalendarTodo expected, CalendarTodo actual) {
        assertThat(expected)
            .as("Verify CalendarTodo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarTodoUpdatableFieldsEquals(CalendarTodo expected, CalendarTodo actual) {
        assertThat(expected)
            .as("Verify CalendarTodo relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getDate()).as("check date").isEqualTo(actual.getDate()))
            .satisfies(e -> assertThat(e.getTime()).as("check time").isEqualTo(actual.getTime()))
            .satisfies(e -> assertThat(e.getDetails()).as("check details").isEqualTo(actual.getDetails()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarTodoUpdatableRelationshipsEquals(CalendarTodo expected, CalendarTodo actual) {
        // empty method
    }
}
