package uz.momoit.lms_canvas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommunityTagAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityTagAllPropertiesEquals(CommunityTag expected, CommunityTag actual) {
        assertCommunityTagAutoGeneratedPropertiesEquals(expected, actual);
        assertCommunityTagAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityTagAllUpdatablePropertiesEquals(CommunityTag expected, CommunityTag actual) {
        assertCommunityTagUpdatableFieldsEquals(expected, actual);
        assertCommunityTagUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityTagAutoGeneratedPropertiesEquals(CommunityTag expected, CommunityTag actual) {
        assertThat(expected)
            .as("Verify CommunityTag auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityTagUpdatableFieldsEquals(CommunityTag expected, CommunityTag actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityTagUpdatableRelationshipsEquals(CommunityTag expected, CommunityTag actual) {
        assertThat(expected)
            .as("Verify CommunityTag relationships")
            .satisfies(e -> assertThat(e.getCommunity()).as("check community").isEqualTo(actual.getCommunity()))
            .satisfies(e -> assertThat(e.getTag()).as("check tag").isEqualTo(actual.getTag()));
    }
}
