package uz.momoit.lms_canvas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommunityAttachmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityAttachmentAllPropertiesEquals(CommunityAttachment expected, CommunityAttachment actual) {
        assertCommunityAttachmentAutoGeneratedPropertiesEquals(expected, actual);
        assertCommunityAttachmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityAttachmentAllUpdatablePropertiesEquals(CommunityAttachment expected, CommunityAttachment actual) {
        assertCommunityAttachmentUpdatableFieldsEquals(expected, actual);
        assertCommunityAttachmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityAttachmentAutoGeneratedPropertiesEquals(CommunityAttachment expected, CommunityAttachment actual) {
        assertThat(expected)
            .as("Verify CommunityAttachment auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityAttachmentUpdatableFieldsEquals(CommunityAttachment expected, CommunityAttachment actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityAttachmentUpdatableRelationshipsEquals(CommunityAttachment expected, CommunityAttachment actual) {
        assertThat(expected)
            .as("Verify CommunityAttachment relationships")
            .satisfies(e -> assertThat(e.getCommunity()).as("check community").isEqualTo(actual.getCommunity()))
            .satisfies(e -> assertThat(e.getAttachment()).as("check attachment").isEqualTo(actual.getAttachment()));
    }
}
