package uz.momoit.lms_canvas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MessageAttachmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageAttachmentAllPropertiesEquals(MessageAttachment expected, MessageAttachment actual) {
        assertMessageAttachmentAutoGeneratedPropertiesEquals(expected, actual);
        assertMessageAttachmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageAttachmentAllUpdatablePropertiesEquals(MessageAttachment expected, MessageAttachment actual) {
        assertMessageAttachmentUpdatableFieldsEquals(expected, actual);
        assertMessageAttachmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageAttachmentAutoGeneratedPropertiesEquals(MessageAttachment expected, MessageAttachment actual) {
        assertThat(expected)
            .as("Verify MessageAttachment auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageAttachmentUpdatableFieldsEquals(MessageAttachment expected, MessageAttachment actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageAttachmentUpdatableRelationshipsEquals(MessageAttachment expected, MessageAttachment actual) {
        assertThat(expected)
            .as("Verify MessageAttachment relationships")
            .satisfies(e -> assertThat(e.getMessage()).as("check message").isEqualTo(actual.getMessage()))
            .satisfies(e -> assertThat(e.getAttachment()).as("check attachment").isEqualTo(actual.getAttachment()));
    }
}
