package uz.momoit.lms_canvas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QuestionGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionGroupAllPropertiesEquals(QuestionGroup expected, QuestionGroup actual) {
        assertQuestionGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertQuestionGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionGroupAllUpdatablePropertiesEquals(QuestionGroup expected, QuestionGroup actual) {
        assertQuestionGroupUpdatableFieldsEquals(expected, actual);
        assertQuestionGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionGroupAutoGeneratedPropertiesEquals(QuestionGroup expected, QuestionGroup actual) {
        assertThat(expected)
            .as("Verify QuestionGroup auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionGroupUpdatableFieldsEquals(QuestionGroup expected, QuestionGroup actual) {
        assertThat(expected)
            .as("Verify QuestionGroup relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionGroupUpdatableRelationshipsEquals(QuestionGroup expected, QuestionGroup actual) {
        assertThat(expected)
            .as("Verify QuestionGroup relationships")
            .satisfies(e -> assertThat(e.getCourse()).as("check course").isEqualTo(actual.getCourse()));
    }
}
